version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rekrutacja-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"