spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rekrutacja-db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
omdb:
  api:
    data-url: http://www.omdbapi.com/
    key: 593c4b95